# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A blog about learning technical stuffs
email: tranphanquocnhan@gmail.com
description: This blog is all about my learning and working on IT technologies, mainly in software development area. Typesafe technology stack (Scala, Akka, Play..) and Cassandra are among the most favourite things I am pursuing to build reactive systems.
url: "http://nhantran.com" # the base hostname & protocol for your site
twitter_username: nhantran
github_username:  nhantran
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Nhân Trần
      layout: "post"
      category: Scala
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

gems: [jekyll-paginate]